//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMahasiswa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_barang
    {
        public int id_barang { get; set; }
        public string nama_barang { get; set; }
        public int harga { get; set; }
        public int stok { get; set; }
        public string nama_supplier { get; set; }
    }
}
